# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' From observed inheritance, determine
#'  inheritance that is been given
#'
#' @param x Observed inheritance vector
#' @param deduction Level of tax deduction
#' @param bounds_legal Bounds for the inheritance
#'    tax rates
#' @param taxes Tax rates to be applied
#' @export
taxation_inheritance <- function(x, deduction, bounds_legal, taxes) {
    .Call(`_REtage_taxation_inheritance`, x, deduction, bounds_legal, taxes)
}

